<?php

declare(strict_types=1);

namespace BrotherTours\OperationsApi\Bookings;

use BrotherTours\OperationsApi\Auth\Csrf;
use WP_REST_Request;

use function BrotherTours\OperationsApi\error;
use function BrotherTours\OperationsApi\response;
use function BrotherTours\OperationsApi\table_exists;

final class BookingsController {
	public function register():void{add_action('rest_api_init',array($this,'routes'));}
	public function routes():void{
		register_rest_route(BTOA_NAMESPACE,'/bookings',array('methods'=>'GET','callback'=>array($this,'list'),'permission_callback'=>static fn(WP_REST_Request $r)=>Csrf::authorize($r,'edit_posts',false)));
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)',array('methods'=>'GET','callback'=>array($this,'get'),'permission_callback'=>static fn(WP_REST_Request $r)=>Csrf::authorize($r,'edit_posts',false)));
	}
	public function list(WP_REST_Request $r){
		global $wpdb;$table=$wpdb->prefix.'wpistic_bookings';if(!table_exists($table))return error('bt_ops_bookings_unavailable',__('Tour Manager bookings table is unavailable.','brother-tours-operations-api'),503);
		$page=max(1,(int)$r->get_param('page'));$per=min(100,max(1,(int)($r->get_param('per_page')?:25)));$where=array('1=1');$args=array();$s=sanitize_text_field((string)$r->get_param('search'));if($s!==''){$like='%'.$wpdb->esc_like($s).'%';$where[]='(reference LIKE %s OR customer_name LIKE %s OR customer_email LIKE %s OR customer_phone LIKE %s)';array_push($args,$like,$like,$like,$like);}foreach(array('type','status','portal_status') as $key){$v=sanitize_key((string)$r->get_param($key));if($v!==''){$where[]="{$key}=%s";$args[]=$v;}}$assigned=absint($r->get_param('assigned_to'));if($assigned){$where[]='assigned_to=%d';$args[]=$assigned;}$tour=absint($r->get_param('tour_id'));if($tour){$where[]='tour_id=%d';$args[]=$tour;}$from=$this->date((string)$r->get_param('from'));if($from){$where[]='created_at >= %s';$args[]=$from.' 00:00:00';}$to=$this->date((string)$r->get_param('to'));if($to){$where[]='created_at <= %s';$args[]=$to.' 23:59:59';}
		$allowed_order=array('id','reference','type','status','portal_status','customer_name','created_at','updated_at');$orderby=sanitize_key((string)$r->get_param('orderby'));$orderby=in_array($orderby,$allowed_order,true)?$orderby:'id';$order='ASC'===strtoupper((string)$r->get_param('order'))?'ASC':'DESC';$where_sql=implode(' AND ',$where);$count_sql="SELECT COUNT(*) FROM {$table} WHERE {$where_sql}";$total=(int)$wpdb->get_var($args?$wpdb->prepare($count_sql,$args):$count_sql);$offset=($page-1)*$per;$sql="SELECT * FROM {$table} WHERE {$where_sql} ORDER BY {$orderby} {$order} LIMIT %d OFFSET %d";$query_args=array_merge($args,array($per,$offset));$rows=$wpdb->get_results($wpdb->prepare($sql,$query_args),ARRAY_A);$items=array_map(fn($row)=>$this->format_row($row),(array)$rows);return response(array('items'=>$items,'total'=>$total,'page'=>$page,'perPage'=>$per,'totalPages'=>(int)ceil($total/$per)));
	}
	public function get(WP_REST_Request $r){
		global $wpdb;$id=(int)$r['id'];$table=$wpdb->prefix.'wpistic_bookings';if(!table_exists($table))return error('bt_ops_bookings_unavailable',__('Tour Manager bookings table is unavailable.','brother-tours-operations-api'),503);$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d",$id),ARRAY_A);if(!$row)return error('bt_ops_booking_not_found',__('Inquiry/booking not found.','brother-tours-operations-api'),404);$tx=$wpdb->prefix.'wpistic_transactions';$audit=$wpdb->prefix.'wpistic_audit_log';$logs=$wpdb->prefix.'wpistic_connection_log';$ing=$wpdb->prefix.'wpistic_form_ingestions';$data=$this->format_row($row);$data['transactions']=table_exists($tx)?array_map(array($this,'format_transaction'),(array)$wpdb->get_results($wpdb->prepare("SELECT * FROM {$tx} WHERE booking_id=%d ORDER BY id DESC",$id),ARRAY_A)):array();$data['activity']=table_exists($audit)?array_map(array($this,'format_audit'),(array)$wpdb->get_results($wpdb->prepare("SELECT * FROM {$audit} WHERE object_type='booking' AND object_id=%d ORDER BY id DESC LIMIT 200",$id),ARRAY_A)):array();$data['connections']=table_exists($logs)?array_map(array($this,'format_connection_log'),(array)$wpdb->get_results($wpdb->prepare("SELECT * FROM {$logs} WHERE response LIKE %s ORDER BY id DESC LIMIT 100",'%'.$wpdb->esc_like((string)$row['reference']).'%'),ARRAY_A)):array();$data['formSource']=null;if(table_exists($ing)){$source=$wpdb->get_row($wpdb->prepare("SELECT source,external_id,form_slug,dispatched,created_at FROM {$ing} WHERE booking_id=%d LIMIT 1",$id),ARRAY_A);if($source)$data['formSource']=$source;}$data['allowedActions']=array();if(class_exists('\\Wpistic\\TourManager\\Booking\\BookingService')){$service=new \Wpistic\TourManager\Booking\BookingService();$data['allowedActions']=$service->lifecycle_actions($id);}return response($data);
	}
	private function format_row(array $row):array{$tour=(int)($row['tour_id']??0);$dep=(int)($row['departure_id']??0);$assigned=(int)($row['assigned_to']??0);$addons=json_decode((string)($row['addons']??''),true);return array('id'=>(int)$row['id'],'reference'=>(string)$row['reference'],'type'=>(string)$row['type'],'status'=>(string)$row['status'],'workflow'=>(string)$row['portal_status'],'tourId'=>$tour,'tour'=>$tour?(string)get_the_title($tour):'','departureId'=>$dep,'departure'=>$dep?array('title'=>(string)get_the_title($dep),'date'=>(string)get_post_meta($dep,'wpistic_dep_date',true)) : null,'customer'=>array('name'=>(string)$row['customer_name'],'email'=>(string)$row['customer_email'],'phone'=>(string)$row['customer_phone'],'country'=>(string)$row['customer_country']),'party'=>array('adults'=>(int)$row['party_adults'],'children'=>(string)$row['party_children']),'hotelPreference'=>(string)$row['hotel_pref'],'addons'=>is_array($addons)?$addons:array(),'specialRequests'=>(string)$row['special_requests'],'currency'=>(string)$row['currency'],'priceAmount'=>(string)$row['price_amount'],'depositAmount'=>(string)$row['deposit_amount'],'balanceAmount'=>(string)$row['balance_amount'],'assignedTo'=>$assigned,'assignedName'=>$assigned?(string)get_the_author_meta('display_name',$assigned):'','sourceUrl'=>(string)$row['source_url'],'createdAt'=>(string)$row['created_at'],'updatedAt'=>(string)$row['updated_at']);}
	private function format_transaction(array $r):array{return array('id'=>(int)$r['id'],'gateway'=>(string)$r['gateway'],'gatewayTransactionId'=>(string)$r['gateway_txn_id'],'type'=>(string)$r['type'],'amount'=>(string)$r['amount'],'currency'=>(string)$r['currency'],'status'=>(string)$r['status'],'createdAt'=>(string)$r['created_at']);}
	private function format_audit(array $r):array{$detail=json_decode((string)$r['detail'],true);return array('id'=>(int)$r['id'],'action'=>(string)$r['action'],'actor'=>(string)$r['actor'],'detail'=>is_array($detail)?$detail:(string)$r['detail'],'createdAt'=>(string)$r['created_at']);}
	private function format_connection_log(array $r):array{return array('id'=>(int)$r['id'],'connectionId'=>(int)$r['connection_id'],'event'=>(string)$r['event'],'statusCode'=>(int)$r['status_code'],'response'=>wp_strip_all_tags(wp_trim_words((string)$r['response'],80,'…')),'attempts'=>(int)$r['attempts'],'createdAt'=>(string)$r['created_at']);}
	private function date(string $v):string{$v=trim($v);return preg_match('/^\d{4}-\d{2}-\d{2}$/',$v)?$v:'';}
}
