<?php

declare(strict_types=1);

namespace BrotherTours\OperationsApi\Bookings;

use BrotherTours\OperationsApi\Auth\Csrf;
use WP_REST_Request;

use function BrotherTours\OperationsApi\error;
use function BrotherTours\OperationsApi\response;

final class BookingActionsController {
	public function register():void{add_action('rest_api_init',array($this,'routes'));}
	public function routes():void{
		$read=static fn(WP_REST_Request $r)=>Csrf::authorize($r,'edit_posts',false);$write=static fn(WP_REST_Request $r)=>Csrf::authorize($r,'edit_posts',true);
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)/actions',array('methods'=>'GET','callback'=>array($this,'actions'),'permission_callback'=>$read));
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)/workflow',array('methods'=>'POST','callback'=>array($this,'workflow'),'permission_callback'=>$write));
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)/assign',array('methods'=>'POST','callback'=>array($this,'assign'),'permission_callback'=>$write));
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)/note',array('methods'=>'POST','callback'=>array($this,'note'),'permission_callback'=>$write));
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)/lifecycle',array('methods'=>'POST','callback'=>array($this,'lifecycle'),'permission_callback'=>$write));
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)/payment-link',array('methods'=>'POST','callback'=>array($this,'payment_link'),'permission_callback'=>$write));
		register_rest_route(BTOA_NAMESPACE,'/bookings/(?P<id>\d+)/dispatch',array('methods'=>'POST','callback'=>array($this,'dispatch'),'permission_callback'=>$write));
	}
	public function actions(WP_REST_Request $r){$service=$this->service();if(!$service)return error('bt_ops_tour_manager_unavailable',__('WPistic Tour Manager is unavailable.','brother-tours-operations-api'),503);$id=(int)$r['id'];if(!$service->get($id))return error('bt_ops_booking_not_found',__('Inquiry/booking not found.','brother-tours-operations-api'),404);return response(array('lifecycle'=>$service->lifecycle_actions($id),'workflow'=>array('new'=>'New','reviewed'=>'Reviewed','sent'=>'Sent','closed'=>'Closed'),'paymentGateways'=>$this->gateways()));}
	public function workflow(WP_REST_Request $r){$service=$this->service();if(!$service)return $this->unavailable();$id=(int)$r['id'];if(!$service->get($id))return $this->not_found();$p=$this->params($r);$status=sanitize_key((string)($p['status']??''));if(!in_array($status,array('new','reviewed','sent','closed'),true))return error('bt_ops_workflow_invalid',__('Invalid workflow status.','brother-tours-operations-api'),422);$service->set_portal_status($id,$status);return response(array('id'=>$id,'workflow'=>$status));}
	public function assign(WP_REST_Request $r){$service=$this->service();if(!$service)return $this->unavailable();$id=(int)$r['id'];if(!$service->get($id))return $this->not_found();$p=$this->params($r);$user=absint($p['userId']??0);if($user && ! get_userdata($user))return error('bt_ops_user_not_found',__('Assigned user not found.','brother-tours-operations-api'),422);$service->assign($id,$user);$service->audit('booking',$id,'assigned',array('user_id'=>$user,'by'=>get_current_user_id()));return response(array('id'=>$id,'assignedTo'=>$user,'assignedName'=>$user?(string)get_the_author_meta('display_name',$user):''));}
	public function note(WP_REST_Request $r){$service=$this->service();if(!$service)return $this->unavailable();$id=(int)$r['id'];if(!$service->get($id))return $this->not_found();$p=$this->params($r);$note=sanitize_textarea_field((string)($p['note']??''));if(trim($note)==='')return error('bt_ops_note_required',__('A note is required.','brother-tours-operations-api'),422);$service->audit('booking',$id,'note',array('note'=>$note));return response(array('id'=>$id,'saved'=>true));}
	public function lifecycle(WP_REST_Request $r){$service=$this->service();if(!$service)return $this->unavailable();$id=(int)$r['id'];if(!$service->get($id))return $this->not_found();$p=$this->params($r);$action=sanitize_key((string)($p['action']??''));$allowed=$service->lifecycle_actions($id);if(!isset($allowed[$action]))return error('bt_ops_lifecycle_not_allowed',__('That lifecycle action is not allowed from the current status.','brother-tours-operations-api'),409,array('allowedActions'=>$allowed));$ok=$service->apply_lifecycle_action($id,$action);return $ok?response(array('id'=>$id,'action'=>$action,'booking'=>$service->get($id))):error('bt_ops_lifecycle_failed',__('Lifecycle update failed.','brother-tours-operations-api'),409);}
	public function payment_link(WP_REST_Request $r){$service=$this->service();if(!$service)return $this->unavailable();$id=(int)$r['id'];if(!$service->get($id))return $this->not_found();$p=$this->params($r);$gateway_id=sanitize_key((string)($p['gateway']??''));$kind=sanitize_key((string)($p['type']??'deposit'));if(!in_array($kind,array('deposit','balance'),true))return error('bt_ops_payment_type_invalid',__('Payment link type must be deposit or balance.','brother-tours-operations-api'),422);if(!class_exists('\\Wpistic\\TourManager\\Payments\\GatewayManager'))return error('bt_ops_gateways_unavailable',__('Payment gateway manager is unavailable.','brother-tours-operations-api'),503);$manager=new \Wpistic\TourManager\Payments\GatewayManager();$manager->register();$gateway=$manager->get($gateway_id);if(!$gateway||!$gateway->isConfigured())return error('bt_ops_gateway_invalid',__('The selected payment gateway is not configured.','brother-tours-operations-api'),422);$result='balance'===$kind?$service->send_balance_link($id,$gateway):$service->send_deposit_link($id,$gateway);if(!$result)return error('bt_ops_payment_link_failed',__('The payment link could not be created from the current booking state or configuration.','brother-tours-operations-api'),409);return response(array('id'=>$id,'type'=>$kind,'gateway'=>$gateway_id,'redirectUrl'=>(string)$result->redirectUrl,'instructions'=>(string)$result->instructions));}
	public function dispatch(WP_REST_Request $r){$service=$this->service();if(!$service)return $this->unavailable();$id=(int)$r['id'];$booking=$service->get($id);if(!$booking)return $this->not_found();if(!class_exists('\\Wpistic\\TourManager\\Connections\\ConnectionsManager'))return error('bt_ops_connections_unavailable',__('Connections engine is unavailable.','brother-tours-operations-api'),503);$p=$this->params($r);$event=sanitize_text_field((string)($p['event']??'inquiry.created'));$allowed=array('inquiry.created','booking.deposit_link','booking.deposit_paid','booking.confirmed','booking.balance_link','booking.balance_paid');if(!in_array($event,$allowed,true))return error('bt_ops_connection_event_invalid',__('Unsupported connection event.','brother-tours-operations-api'),422);$manager=new \Wpistic\TourManager\Connections\ConnectionsManager();$manager->dispatch($event,$booking);if('inquiry.created'===$event)$service->set_portal_status($id,'sent');$service->audit('booking',$id,'connection_dispatch',array('event'=>$event));return response(array('id'=>$id,'event'=>$event,'dispatched'=>true));}
	private function service(){return class_exists('\\Wpistic\\TourManager\\Booking\\BookingService')?new \Wpistic\TourManager\Booking\BookingService():null;}
	private function gateways():array{if(!class_exists('\\Wpistic\\TourManager\\Payments\\GatewayManager'))return array();$m=new \Wpistic\TourManager\Payments\GatewayManager();$m->register();$out=array();foreach($m->all() as $id=>$g)$out[]=array('id'=>(string)$id,'name'=>(string)$g->displayName(),'configured'=>(bool)$g->isConfigured());return $out;}
	private function params(WP_REST_Request $r):array{$j=$r->get_json_params();return is_array($j)?$j:$r->get_params();}private function unavailable(){return error('bt_ops_tour_manager_unavailable',__('WPistic Tour Manager is unavailable.','brother-tours-operations-api'),503);}private function not_found(){return error('bt_ops_booking_not_found',__('Inquiry/booking not found.','brother-tours-operations-api'),404);}
}
